server:
  port: 8089
spring:
  cloud:
    inetutils:
      preferred-networks: 192.168.44.*
    #spring:
#  cloud:
 #   agamotto:
 #     config:
   #     enabled: true
    discovery:
      enabled: true
property.from.sample.custom.source: adasdasd23232111111111111111111111111111111111111111111
  #config:
   #import: optional:agamotto-cloud:xx
logging:
  level:
    org.agamotto: debug