// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimpleSample.proto

package org.agamotto.cloud.sample.grpc.proto;

public final class SampleGrpc {
  private SampleGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleSampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleSampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleSampleReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleSampleReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SimpleSample.proto\"#\n\023SimpleSampleRequ" +
      "est\022\014\n\004name\030\001 \001(\t\"$\n\021SimpleSampleReply\022\017" +
      "\n\007message\030\001 \001(\t2D\n\014SimpleSample\0224\n\010SayHe" +
      "llo\022\024.SimpleSampleRequest\032\022.SimpleSample" +
      "ReplyB4\n$org.agamotto.cloud.sample.grpc." +
      "protoB\nSampleGrpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SimpleSampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SimpleSampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleSampleRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_SimpleSampleReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SimpleSampleReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleSampleReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
