// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimpleSample.proto

package org.agamotto.cloud.sample.grpc.proto;

public interface SimpleSampleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleSampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
