name: Publish package to GitHub Packages
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
      repository-projects: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: agamotto-dev-commons
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
        - name: Publish package
            run: mvn --batch-mode deploy
            env:
              MAVEN_USERNAME: ${{ secrets.CODING_USERNAME }}
              MAVEN_PASSWORD: ${{ secrets.CODING_PASSWORD }}
