name: 推送至腾讯maven仓库中
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 打包编译
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: agamotto-dev-commons
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: 推送
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.CODING_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CODING_PASSWORD }}
